language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose
  - cargo test --verbose --no-run
  - cargo doc --verbose --no-deps
